name: authentication
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^7.9.0
  design:
    path: ../../core/design
  flutter:
    sdk: flutter
  local_auth: ^2.2.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.2.5

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
