name: pinet_app
description: "PINET Mobile App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  configuration:
    path: packages/core/configuration
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  melos: ^5.2.1

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: packages/core/design/fonts/RobotoCondensed-VariableFont_wght.ttf
          style: normal
        - asset: packages/core/design/fonts/RobotoCondensed-Italic-VariableFont_wght.ttf
          style: italic
    - family: Eczar
      fonts:
        - asset: packages/core/design/fonts/Eczar-VariableFont_wght.ttf
    - family: CustomIcons
      fonts:
        - asset: packages/core/design/fonts/CustomIcons.ttf
