name: configuration
description: "Initialize app configuration"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  # Internal Packages
  common:
    path: ../common
  design:
    path: ../design
  routing:
    path: ../routing
  # End of Internal Packages

  envied: ^0.5.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
