name: routing
description: "PINET Mobile App Routing"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  # Internal Packages
  dashboard:
    path: ../../features/dashboard
  # End of Internal Packages
  
  auto_route: ^7.8.4
  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true