name: routing
description: "PINET Mobile App Routing"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  animations: ^2.0.11
  authentication:
    path: ../../features/authentication
  auto_route: ^7.9.0
  dashboard:
    path: ../../features/dashboard
  design:
    path: ../design
  flutter:
    sdk: flutter
  settings:
    path: ../../features/settings
  transaction:
    path: ../../features/transaction

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
